# Generated by Django 4.1.7 on 2023-11-07 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operation_Execution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=25)),
                ('course_name', models.CharField(max_length=20)),
                ('duration', models.IntegerField()),
                ('seat', models.IntegerField()),
            ],
        ),
    ]
